import { InvestmentPlanType } from "@/app/types/investmentPlan";

export const investmentPlans: InvestmentPlanType[] = [
   {
    id: 'zyx-drone',
    title: 'Zyx Drone',
    description: 'A basic reconnaissance specimen from the Zyx nebula',
    imagePath: '/plans/miner1.png',
    altText: 'Zyx Drone - Scout Class Xenomorph',
    rendimiento: 1.2,
    monto: 20,
    minPrice: 20,
    maxPrice: 400,
    duracionDias: 365,
    titleKey: 'plans.zyxDrone.title',
    descriptionKey: 'plans.zyxDrone.description',
  },
  {
    id: 'plan-17',
    title: 'Plan 1.7%',
    description: '1.7% diario durante 1 año. Compra única por usuario. Se activa solo si tienes un depósito confirmado hoy.',
    imagePath: '/plans/miner8.png',
    altText: 'Plan 1.7%',
    rendimiento: 1.7,
    monto: 50,
    minPrice: 50,
    maxPrice: 400,
    duracionDias: 365,
    titleKey: 'plans.plan17.title',
    descriptionKey: 'plans.plan17.description',
    maxPerUser: 1,
  },
  {
    id: 'plan-20',
    title: 'Plan 2.5%',
    description: '2.5% diario durante 1 año. Compra única por usuario. Se activa solo si tienes un depósito confirmado hoy.',
    imagePath: '/plans/miner6.png',
    altText: 'Plan 2.5%',
    rendimiento: 2.5,
    monto: 100,
    minPrice: 100,
    maxPrice: 400,
    duracionDias: 365,
    titleKey: 'plans.plan20.title',
    descriptionKey: 'plans.plan20.description',
    maxPerUser: 1,
  },
  {
    id: 'plan-23',
    title: 'Plan 2.3%',
    description: '2.3% diario durante 1 año. Compra única por usuario. Se activa solo si tienes un depósito confirmado hoy.',
    imagePath: '/plans/aliensc.png',
    altText: 'Plan 2.3%',
    rendimiento: 2.3,
    monto: 120,
    minPrice: 120,
    maxPrice: 400,
    duracionDias: 365,
    titleKey: 'plans.plan23.title',
    descriptionKey: 'plans.plan23.description',
    maxPerUser: 1,
  },
  {
    id: 'plan-28',
    title: 'Plan 2.8%',
    description: '2.8% diario durante 1 año. Compra única por usuario.',
    imagePath: '/plans/miner5.png',
    altText: 'Plan 2.8%',
    rendimiento: 2.8,
    monto: 150,
    minPrice: 150,
    maxPrice: 800,
    duracionDias: 365,
    titleKey: 'plans.plan28.title',
    descriptionKey: 'plans.plan28.description',
    maxPerUser: 1,
  },
 
  // {
  //   id: 'nova-boost',
  //   title: 'Nova Boost',
  //   description: 'Limited boost: 1.8% for the first 10 days, then 1.2%',
  //   imagePath: '/plans/miner6.png',
  //   altText: 'Nova Boost - Limited Boost Plan',
  //   rendimiento: 1.8,
  //   monto: 50,
  //   minPrice: 50,
  //   maxPrice: 100,
  //   duracionDias: 365,
  //   titleKey: 'plans.novaBoost.title',
  //   descriptionKey: 'plans.novaBoost.description',
  // },
  {
    id: 'vortex-hunter',
    title: 'Vortex Hunter',
    description: 'Predatory species specialized in plasma extraction',
    imagePath: '/plans/miner2.png',
    altText: 'Vortex Hunter - Predator Class',
    rendimiento: 1.3,
    monto: 50,
    minPrice: 50,
    maxPrice: 700,
    duracionDias: 365,
    titleKey: 'plans.vortexHunter.title',
    descriptionKey: 'plans.vortexHunter.description',
  },
  {
    id: 'nebula-sentinel',
    title: 'Nebula Sentinel',
    description: 'Elite guardian of the cosmic frontier',
    imagePath: '/plans/miner3.png',
    altText: 'Nebula Sentinel - Guardian Class',
    rendimiento: 1.5,
    monto: 90,
    minPrice: 90,
    maxPrice: 1000,
    duracionDias: 365,
    titleKey: 'plans.nebulaSentinel.title',
    descriptionKey: 'plans.nebulaSentinel.description',
    maxPerUser: 1,
  },
  {
    id: 'plasma-wraith',
    title: 'Plasma Wraith',
    description: 'Ethereal being that feeds on raw plasma energy',
    imagePath: '/plans/miner4.png',
    altText: 'Plasma Wraith - Ethereal Class',
    rendimiento: 1.8,
    monto: 120,
    minPrice: 120,
    maxPrice: 1300,
    duracionDias: 365,
    titleKey: 'plans.plasmaWraith.title',
    descriptionKey: 'plans.plasmaWraith.description',
  },
  {
    id: 'crimson-overlord',
    title: 'Crimson Overlord',
    description: 'Supreme commander of the hive colonies',
    imagePath: '/plans/miner5.png',
    altText: 'Crimson Overlord - Commander Class',
    rendimiento: 2,
    monto: 401,
    minPrice: 401,
    maxPrice: 1800,
    duracionDias: 365,
    titleKey: 'plans.crimsonOverlord.title',
    descriptionKey: 'plans.crimsonOverlord.description',
  },
  // {
  //   id: 'void-emperor',
  //   title: 'Void Emperor',
  //   description: 'Ancient ruler from the dark void between galaxies',
  //   imagePath: '/plans/miner6.png',
  //   altText: 'Void Emperor - Legendary Class',
  //   rendimiento: 2.5,
  //   monto: 250,
  //   duracionDias: 250,
  //   titleKey: 'plans.voidEmperor.title',
  //   descriptionKey: 'plans.voidEmperor.description',
  // },
  // {
  //   id: 'spore-hatchling',
  //   title: 'Spore Hatchling',
  //   description: 'Newly spawned creature with growth potential',
  //   imagePath: '/plans/miner7.png',
  //   altText: 'Spore Hatchling - Larva Class',
  //   rendimiento: 0.5,
  //   monto: 15,
  //   duracionDias: 300,
  //   titleKey: 'plans.sporeHatchling.title',
  //   descriptionKey: 'plans.sporeHatchling.description',
  // },
  // {
  //   id: 'quantum-shifter',
  //   title: 'Quantum Shifter',
  //   description: 'Phase-shifting entity from parallel dimensions',
  //   imagePath: '/plans/miner8.png',
  //   altText: 'Quantum Shifter - Dimensional Class',
  //   rendimiento: 1.3,
  //   monto: 35,
  //   duracionDias: 300,
  //   titleKey: 'plans.quantumShifter.title',
  //   descriptionKey: 'plans.quantumShifter.description',
  // },
];
